baseURL = 'https://Antonio-Parada.github.io/kgimd/'
languageCode = 'en-us'
title = 'Kgimd Branding Agency'
theme = 'congo'

[menu]
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 10
  [[menu.main]]
    identifier = "clients"
    name = "Clients"
    url = "/clients/"
    weight = 20
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 30